#ifndef ERUPTOR_EVENT_KEYS_HPP
#define ERUPTOR_EVENT_KEYS_HPP

namespace eruptor::event
{

enum class Key
{
    NONE,
    ESC, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, PRTSC, SCRLK, PAUSE,
    BACKTIC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, MINUS, PLUS, BACKSPACE, INS, HOME, PGUP, NUM, BACKSLASH, ASTERISK, NUM_MINUS,
    TAB, Q, W, E ,R, T, Y ,U, I, O, P, LEFT_BRASKET, RIGHT_BRASKET, SLASH, DEL, END, PGDN, NUM_7, NUM_8, NUM_9, NUM_PLUS,
    CAPSLOCK, A, S, D, F, G, H, J, K, L, SEMICOLOM, APOSTROFE, ENTER, NUM_4, NUM_5, MUM_6,
    LEFT_SHIFT, Z, X, C, V, B, N, M, TRI_LEFT_BRASKET, TRI_RIGHT_BRASKET, QUESTION_MARK, RIGHT_SHIFT, UP, NUM_1, NUM_2, NUM_3, NUM_ENTER,
    LEFT_CTRL, POWER, LEFT_ALT, SPACE, RIGHT_ALT, FN, RIGHT_CTR, LEFT, DOWN, RIGHT, NUM_0, NUM_COMMA,
};

}

#endif //ERUPTOR_EVENT_KEYS_HPP
